#version: '3.8'
services:
  postgresql:
    image: postgres
    command: -c 'max_connections=1000'
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: "apis"
      POSTGRES_USER: "apis"
      POSTGRES_DB: "lending_platform"
    env_file:
      - .env
    networks:
      - default

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # ---- KRaft basics ----
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # ---- Listeners ----
      KAFKA_LISTENERS: >
        INTERNAL://0.0.0.0:29092,
        EXTERNAL://0.0.0.0:9092,
        CONTROLLER://0.0.0.0:9093

      KAFKA_ADVERTISED_LISTENERS: >
        INTERNAL://kafka:29092,
        EXTERNAL://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        INTERNAL:PLAINTEXT,
        EXTERNAL:PLAINTEXT,
        CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # ---- Single-node sanity ----
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - default

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      JVM_OPTS: "-Xms512M -Xmx512M"
      KAFKA_BROKERCONNECT: "kafka:29092"
    networks:
      - default
  auth-server:
    build: ./auth-server
    depends_on:
      - postgresql
    ports:
      - "9000:9000"

  orchestrator:
    build: ./ms-orchestrator
    depends_on:
      - kafka
      - postgresql
    ports:
      - "8080:8080"

  loan-disbursement:
    build: ./ms-loan-disbursement
    depends_on:
      - kafka
      - postgresql

  loan-repayment:
    build: ./ms-loan-repayment
    depends_on:
      - kafka
      - postgresql

  product-configuration:
    build: ./ms-product-configurations
    depends_on:
      - postgresql
      - kafka

  notification:
    build: ./ms-notification
    depends_on:
      - postgresql
      - kafka

  gateway:
    build: ./ms-gateway
    depends_on:
      - postgresql
      - kafka

  crm:
    build: ./ms-crm
    depends_on:
      - postgresql
      - kafka


  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 9000:80
networks:
  default:


