package ke.co.interviewusercaseworld.commons.enums;

public enum CommandsEnum {
    DISBURSE_COMMAND, REPAYMENT_COMMAND, NOTIFY_COMMAND,PRODUCT_VALIDATION_COMMAND,USER_VALIDATION_COMMAND
    ,DISBURSE_EVENT, REPAYMENT_EVENT, NOTIFY_EVENT,PRODUCT_VALIDATION_EVENT,USER_VALIDATION_EVENT,ACTUAL_REPAYMENT_COMMAND,
    REPAYMENT_SCHEDULING_EVENT,REPAYMENT_SCHEDULING_COMMAND,REPAYMENT_PREVALIDATION_COMMAND,REPAYMENT_PREVALIDATION_EVENT
}
