package ke.co.interviewusercaseworld.commons.enums;

public enum NotificationTemplateEnum {
    PRODUCT_VALIDATION_FAILED_TEMPLATE,
    USER_VALIDATION_FAILED_TEMPLATE,
    DISBURSAL_FAILED_TEMPLATE,
    REPAYMENT_FAILED_TEMPLATE,
    SUCCESSFUL_LOAN_DISBURSEMENT,
    REPAYMENT_PREVALIDATION_FAILED_TEMPLATE,
    REPAYMENT_SUCCESSFUL_TEMPLATE,
}
