package ke.co.interviewusercaseworld.commons.enums;

public enum OperationNameEnum {
    UNSPECIFIED, JWT_PROCESSING, CORS_CONFIGURATION, PRODUCT_CREATION,LOAN_PRODUCT_CONFIGURATION,
    LOAN_PRODUCT_RETRIEVAL,TOKEN_REQUEST_HANDLING, USER_DETAILS_RETRIEVAL, JWT_AUTHENTICATION, ACCOUNT_STATUS_VALIDATION, ACCOUNT_UPDATE, LOAN_APPLICATION, CREDENTIAL_VALIDATION,
    USER_VALIDATION, KAFKA_TOPIC_CONFIGURATION, PUBLISH_OUTBOX_EVENTS_TASK, KAFKA_CONSUMER, DISBURSEMENT_TO_WALLET, LOAN_DISBURSEMENT, USER_CREATION
}
