package ke.co.interviewusercaseworld.commons.enums;

public enum OperationNameEnum {
    UNSPECIFIED, JWT_PROCESSING, CORS_CONFIGURATION, PRODUCT_CREATION,LOAN_PRODUCT_CONFIGURATION,
    LOAN_PRODUCT_RETRIEVAL,TOKEN_REQUEST_HANDLING, USER_DETAILS_RETRIEVAL, JWT_AUTHENTICATION, ACCOUNT_STATUS_VALIDATION, ACCOUNT_UPDATE, LOAN_APPLICATION, CREDENTIAL_VALIDATION,
    USER_VALIDATION, KAFKA_TOPIC_CONFIGURATION, PUBLISH_OUTBOX_EVENTS_TASK, KAFKA_CONSUMER, DISBURSEMENT_TO_WALLET, LOAN_DISBURSEMENT, REPAYMENT_SCHEDULING, USER_CREATION,
    LOAN_QUERY, NOTIFICATION_JOB, SMS_NOTIFICATION, EMAIL_NOTIFICATION, OUTBOX_EVENTS_SCHEDUING, UPDATE_OUTBOX_EVENT_STATUS, JOB_SCHEDULING, SAGA_QUERY, LOAN_SCHEDULE_CALCULATION, LOAN_REPAYMENT,
    FLAT_RATE_SCHEDULE_GENERATION, LOAN_SCHEDULE_GENERATION, REPAYMENT_NOTIFICATION, REDUCING_BALANCE_SCHEDULE_GENERATION

}
