spring:
  application:
    name: ms-discovery
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/lending_platform
    username: apis
    password: apis
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    locations: classpath:db/migrations
    encoding: UTF-8
    validate-on-migrate: true
    clean-disabled: true